### ISSUE TITLE
Question about colmap output

### ISSUE THREAD

**Issue by TLB-MISS** [facebookresearch/vggsfm#69]
There are many coordinates in `POINTS2D[]` of `images.txt` that exceed the resolution of the original image. 
I guess it is because the camera is `SIMPLE_RADIAL`, so the pixel coordinates of the undistorted image are recorded.
But when I transform them using `f`, `cx`, `cy`, and `k1`, there are still points that are outside the original image resolution(In fact, all `k1` in `cameras.txt` are negative numbers, so it doesn't seem to be a proper conversion.).
What exactly does `POINTS2D[]` in `images.txt` mean? 
If they are not points in the original image space, how can I convert them to points in the original image space?
It would be helpful if you could tell me the conversion formula briefly. 

Thank you.

**Comment by jytime** [comment]
Hey this is because our method (1) first rescales all the images to 1024x1024, (2) run reconstruction, and (3) resize the camera parameters to original resolution. By default, we do not rescale the 2D key points because they are usually not used later. But if you want, just set ```shift_point2d_to_original_res=True```, and you will get the 2D key points in the original resolution.

FYI: https://github.com/facebookresearch/vggsfm/issues/36

**Comment by TLB-MISS** [comment]
@jytime 
Oh, sorry. I didn't check properly. Thanks for the reply!

I have one more question. Is it possible to run vggsfm from initial rough camera poses?

**Comment by jytime** [comment]
Hi yes you can but generally it will not bring more gains. You can just replace the inputs to our triangulator by your own input.

**Comment by TLB-MISS** [comment]
I see! Since vggsfm is so robust, it doesn't really feel strange that there isn't much gain.
Thank you so much for always giving very quick feedback!
