### ISSUE TITLE
Run only Triangulation with own camera poses 

### ISSUE THREAD

**Issue by albb20** [facebookresearch/vggsfm#82]
Hey, 

i have a similar question as #41, but additionally wanted to know how I can run only the triangulation in VGGSfM, skipping the both previous steps. I just want the (dense) point cloud, not necessarily with camera pose estimation. 
I checked the scripts but did not find a way to modify them for my needs, since i did not fully understand the programming. 
A small example would be really helpful.
Thanks!

**Comment by jytime** [comment]
Hey @albb20 ,

Since you mentioned you only want triangulation, so we assume you already have accurate ```extrinsics``` and ```intrinsics``` which may come from other sources. Please note that camera parameters are necessary for triangulation, no matter they come from vggsfm or other sources.

Therefore, you just need to use the runner to predict tracks on your input images, 

https://github.com/facebookresearch/vggsfm/blob/8a3fe9d8ac0af7fe3324b8afde1a387eaa9b7f70/vggsfm/runners/runner.py#L419

and then feed these ```pred_track, pred_vis, pred_score``` as below:

```
        tracks_normalized_refined = normalize_tracks(pred_tracks, intrinsics)
        best_triangulated_points, best_inlier_num, best_inlier_mask = triangulate_tracks(
            extrinsics, tracks_normalized_refined, track_vis=pred_vis, track_score=pred_score, max_ransac_iters=128
        )

```

Here ```best_triangulated_points``` is the point cloud you will need.
